"""Build the two canonical research notebooks and their separate task-folder indexes."""
from pathlib import Path
import json
import nbformat as nbf

ROOT = Path(__file__).resolve().parents[2]
M = nbf.v4.new_markdown_cell
C = nbf.v4.new_code_cell
SETUP = "%pip install -q duckdb huggingface_hub pandas scikit-learn matplotlib"
BOOTSTRAP = '''from pathlib import Path
import sys, json, subprocess
import pandas as pd
from IPython.display import display, Image
candidate = Path.cwd().resolve()
ROOT = next((path for path in [candidate, *candidate.parents]
             if (path / "data/raw/content_refresh_anonymized.csv").exists()), None)
if ROOT is None:
    own_repo = "https://github.com/Hamza2-2/flyrank-ai-internship"
    clone_root = candidate / "flyrank-ai-internship"
    if not clone_root.exists():
        subprocess.run(["git", "clone", "--depth", "1", own_repo, str(clone_root)],
                       check=True, capture_output=True, text=True)
    if not (clone_root / "data/raw/content_refresh_anonymized.csv").exists():
        raise FileNotFoundError("The owned repository checkout has no starter CSV; verify the public repository and rerun.")
    ROOT = clone_root.resolve()
sys.path.insert(0, str(ROOT / "work/scripts"))
from capstone_analysis import load_data, FEATURES, BANNED, run_study
'''


def write_notebook(path, cells):
    nb = nbf.v4.new_notebook(cells=cells)
    nb.metadata["kernelspec"] = {"display_name": "Python 3 (FlyRank)", "language": "python", "name": "flyrank"}
    nb.metadata["language_info"] = {"name": "python", "version": "3.11"}
    nbf.write(nb, str(path))


def build():
    metrics = json.loads((ROOT / "work/outputs/capstone_metrics.json").read_text(encoding="utf-8"))
    numbers = metrics["data"]
    winner = metrics["selected_model"]
    result = metrics["test_metrics"][winner]
    baseline = metrics["test_metrics"]["rule_baseline"]
    notebooks = ROOT / "work/notebooks"
    assignment = ROOT / "work/assignments/ML-02_Research_Question_and_Provisional_Lane"
    capstone = ROOT / "work/capstones/ML_Google_Search_Ranking_and_Discoverability"
    for folder in [assignment, capstone]:
        folder.mkdir(parents=True, exist_ok=True)
    research_cells = [
        C(SETUP),
        M("# ML-02 — Research Question and Provisional Lane\n\nAuthor: Hamza Afzal · 9 October 2026.\n\nThis notebook contains the framing and measured starter evidence. Canonical deliverable: `work/notebooks/w01_research_question.ipynb`. The separate task folder is an index to this notebook; the original assignment structure is preserved."),
        M("## 1. My lane and why\n\n**Ranking Signal Analysis**, with explainable content-review priorities as the decision output. I will study which content, freshness, search and engagement signals are associated with observed impression decline across held-out clients. This lane is explicitly supported by the 30,000-row starter dataset in the repository lane guide. It supports useful signal auditing and a transparent queue before a more demanding warehouse time-series study. A classifier is an association tool here; the deliverable is a signal report and careful editorial recommendations."),
        C(BOOTSTRAP + "frame, features, target, numbers = load_data()\nprint('Chosen lane: Ranking Signal Analysis')\nprint('Unit: one pseudonymized content item; client used only for grouping')"),
        M("## 2. The question: decision, action, cost of a wrong call\n\n**Question:** On clients withheld from model fitting, which safe content and current-window performance signals distinguish pages with measured impression decline, and can these signals prioritize an editor's first 50 reviews better than a transparent freshness/visibility rule?\n\n**Decision and actor:** An SEO/content editor chooses which sufficiently visible pages to inspect first. **Unit:** one page; the client is the independent validation group. **Output:** a signal report and ranked review cases, each with an inspectable reason code. **Action:** verify the latest search evidence, then check metadata, factual freshness, coverage or instrumentation; edits require human judgment. **Cost:** an incorrect priority consumes editor time or risks unnecessary changes; a missed priority delays attention to a potentially important decline. No costs are invented in currency.\n\n**Why data can help:** the transparent rule is the starting point, because it is cheap and explainable. Multiple correlated signals may combine differently across clients, so a fixed logistic model and conservative forest can test whether association beyond that rule is measurable. If they fail, retain the rule. **Metric fixed before fitting:** average precision and precision@50 against the held-out proxy base rate; inspect client variability.\n\n**Target caution:** `trend_direction == 'down'` is a deterministic bucket of an observed current-window change, not an observed future outcome or a label of editorial benefit. Future decline requires earlier feature windows and a later warehouse outcome."),
        C("assert not set(features.columns) & BANNED\nassert frame.content_id.is_unique\nprint('Duplicate page IDs:', int(frame.content_id.duplicated().sum()))\nprint('Forbidden model features:', sorted(set(features.columns) & BANNED))"),
        M("## 3. Quick look at the data: real numbers\n\nThe code loads the bundled CSV locally and publishes only aggregates. Row counts establish available evidence; the current decline proxy and stale-visible count establish why a content-review signal study is worth pursuing. The counts are measured, not borrowed from the example pipeline."),
        C("support = pd.DataFrame([\n    {'measure': 'Starter content items', 'value': numbers['rows']},\n    {'measure': 'Client validation groups', 'value': numbers['clients']},\n    {'measure': 'Current-decline proxy items', 'value': numbers['declining_rows']},\n    {'measure': 'Current-decline proxy share', 'value': round(numbers['declining_share'], 4)},\n    {'measure': 'Stale and visible: update >=180 days, impressions >=500', 'value': numbers['stale_visible_rows']},\n    {'measure': 'Missing position (zero sentinel)', 'value': numbers['no_position_rows']},\n])\ndisplay(support)\nprint('The share is a fraction; source rate columns such as ctr use percentage units.')"),
        M("## 4. Careful words: what I can and cannot claim\n\nI can report **observed associations**, measured discrimination on unseen client groups, negative results, and **decision-support** review priorities. I cannot claim future decline prediction, Google's ranking factors, causal refresh impact, a guaranteed useful edit, or generalization to the full warehouse. Aggregate 90-day features overlap the proxy window, even after excluding trend fields; that prevents a prospective claim. Position zero is missing measurement, rate columns are percentages, and missing depth/keyword data must be flagged. No IDs, trend fields, provider/model names or six last/previous-30-day trend inputs enter the features.\n\nThe full-warehouse extension is pending authorized Hugging Face access. The starter study can run without that account."),
        C("print(json.dumps({\n    'rates_are_percentages': True,\n    'position_zero_is_missing': True,\n    'grouping_id_in_features': bool({'client_id','content_id'} & set(features.columns)),\n    'future_outcome_available': False,\n    'public_outputs_are_aggregate': True,\n}, indent=2))"),
        M("## 5. Self-check\n\n- [x] One supported lane, one decision, one actor and concrete review actions.\n- [x] Page unit, output, error cost and a fair rule comparison are stated.\n- [x] More than two measured supporting numbers are generated from the CSV.\n- [x] ID/label exclusions and same-window limitations are explicit.\n- [x] Notebook executed top to bottom after authoring.\n- [ ] Intern validates the framing as their own work.\n- [ ] Commit to an owned public repository and submit that repository URL.\n\nAssistant assistance: code and document drafting. Hamza must review the decisions and explain the method; this notebook does not claim personal manual work or a portal submission."),
    ]
    write_notebook(notebooks / "w01_research_question.ipynb", research_cells)
    capstone_cells = [
        C(SETUP),
        M("# Ranking Signal Analysis: explainable content-review priorities\n\nHamza Afzal · 9 October 2026 · Machine Learning capstone\n\n**Scope:** completed, reproducible local starter study. Full warehouse analysis, intern validation and public submission are pending. The attached brief points to the full warehouse; the lane guide allows starter analysis. This notebook documents the distinction so the starter results cannot be mistaken for full-release results."),
        M(f"## Abstract\n\nThis study asks whether safe content and contemporaneous search signals can prioritize review of pages associated with observed impression decline on clients held out from training. It uses {numbers['rows']:,} starter content items across {numbers['clients']} pseudonymized clients, with a current-window decline bucket as a proxy. A transparent training-fitted rule, logistic regression and a conservative random forest are compared using client-grouped training, validation and test partitions. The validation-selected {winner.replace('_',' ')} achieved held-out average precision {result['average_precision']:.3f} versus {baseline['average_precision']:.3f} for the rule, with precision@50 {result['precision_at_50']:.3f} versus {baseline['precision_at_50']:.3f}. The signal audit and reason-coded queue support human inspection and do not establish future decline prediction or causal editorial benefit."),
        M("## 1. Question and introduction\n\nAn editor has a limited review budget and needs an evidence-based starting list. The unit is a page, and the action is inspection before any content change. Which safe signals are associated with the current decline proxy across clients, and does their combination improve top-50 review discrimination over an explainable rule? Wasted review time and delayed attention are the error costs. The queue never automatically edits, merges or prunes content. The professional demonstration is a reproducible backend-compatible analysis pipeline, while the editorial decision remains the research focus."),
        C(BOOTSTRAP + "study = run_study()\nprint('Local pipeline regenerated aggregate evidence and charts.')"),
        M("## 2. Data and safety\n\nThe bundled `data/raw/content_refresh_anonymized.csv` has one content item per row and trailing-90-day aggregates. The starter dictionary does not specify an exact calendar end date, so no warehouse date window is assigned to it. Eligibility requires positive impressions and content age at least 90 days. Grain and duplicate checks run before modeling. IDs are used locally for joins/splits, never as features; public outputs show aggregate statistics and synthetic review-case labels. The small local case-to-pseudonym lookup CSV is ignored by git. No raw warehouse export, names, domains, URLs, queries or credentials are published.\n\nPosition zero becomes missing measurement; missing keyword/depth/scroll observations receive explicit flags. Median imputation is fitted on training only, and rates retain their documented percentage units. Scroll rates above 100 are not silently clipped, because measurement systems differ. Provider/model names, redundant derived tiers and all last/previous-30-day trend inputs are excluded. No full-warehouse facts have been queried."),
        C("display(pd.DataFrame([study['data']]).T.rename(columns={0:'measured value'}))\ndisplay(pd.DataFrame(study['split']).T)\nprint('Model columns:', study['feature_columns'])"),
        M("## 3. Methodology, baseline and leakage audit\n\n**Proxy:** `trend_direction == down`, defined by a measured decline beyond 20% between two current 30-day impression windows. This is not a future target or an editor-utility label. All six window components and both trend columns are banned as features.\n\n**Rule fixed before fitting:** 40% visibility, 30% freshness, 25% visibility-adjusted position opportunity, and 5% visibility-adjusted depth gap. Visibility, freshness and depth use empirical cumulative distributions fitted on training clients for validation and development clients for final testing. Missing depth and missing position add no opportunity bonus. The rule uses no target field.\n\n**Models fixed before test:** logistic regression (C=1, 1,500 iterations) and 180-tree forest (depth 10, leaf floor 25, square-root feature subsampling). Numeric imputation, scaling for logistic regression, and categorical encoding are fitted within each training pipeline. No hyperparameter search uses test outcomes. The model with highest validation average precision is selected, then refitted on training plus validation.\n\n**Validation:** 25% of clients held out for test (seed 2026), and 25% of remaining clients for validation (seed 2027). Client sets cannot overlap. Both baseline and models see identical partitions. Client-bootstrap intervals use 400 draws and preserve within-client dependence, but eight test clusters limit precision. A shuffled-training-label control is evaluated only on validation. Validation permutation importance and a fixed metadata-only ablation audit where association comes from. Rerunning the notebook reproduces the same held-out result; it is not fresh independent confirmation."),
        C("display(pd.DataFrame(study['validation_metrics']).T)\nprint('Selected by validation AP:', study['selected_model'])\nprint(json.dumps(study['leakage_audit'], indent=2))"),
        M("## 4. Results: model and baseline on the same split\n\nAverage precision is evaluated beside the proxy base rate; precision@50 is tied to an explicit review budget. The operational subset uses at least 500 impressions, and its model and baseline metrics are reported separately on the same subset. The rule score is not claimed to be a calibrated probability. Model outputs are used as ranking scores; calibration to future editorial value has not been established."),
        C("display(pd.DataFrame(study['test_metrics']).T)\ndisplay(pd.DataFrame(study['review_eligible_test_metrics']).T)\nprint(json.dumps(study['client_bootstrap_intervals'], indent=2))\ndisplay(Image(filename=str(ROOT/'work/figures/capstone_precision_recall.png')))\ndisplay(Image(filename=str(ROOT/'work/figures/capstone_review_budget.png')))"),
        M("## 5. Interpretation and error analysis\n\nPermutation importance measures association in the validation sample, conditional on this model and its correlated feature set; it is not a causal ranking-factor estimate. The metadata-only ablation excludes all traffic totals, day-coverage variables and rates. Per-client and missingness strata reveal whether a global result conceals uneven behavior. A proxy-negative top-ranked item is not proved to be wasted editorial effort, and a proxy-positive item is not proved to benefit from editing."),
        C("audit = json.loads((ROOT/'work/outputs/capstone_feature_audit.json').read_text(encoding='utf-8'))\ndisplay(pd.DataFrame(audit).sort_values('ap_drop_mean', ascending=False).head(10))\ndisplay(Image(filename=str(ROOT/'work/figures/capstone_feature_audit.png')))\ndisplay(pd.DataFrame(study['per_client_metrics']))\ndisplay(pd.DataFrame(study['subgroup_metrics']))\nprint(json.dumps(study['metadata_only_ablation'], indent=2))\nprint(json.dumps(study['error_analysis'], indent=2))"),
        M("## 6. Ranked recommendations and action playbook\n\nEligible held-out starter cases (at least 500 impressions) are ordered by the selected model's current-proxy score. Actions and reason codes use observable context; target labels never enter action generation. Missing position triggers an instrumentation check; low CTR at a measured position up to 20 triggers metadata/intent review; limited depth triggers coverage review; stale content triggers factual checking; other cases trigger monitoring. For the first 20, an editor should confirm measurement, inspect the real content in an authorized system, record accept/reject and reasoning, and edit only after that review. Those content checks cannot be completed from an anonymized numerical export. This bounded queue demonstrates an actionable interface without publishing identifying rows. The ignored local lookup supports authorized joins to pseudonymized pages."),
        C("queue = json.loads((ROOT/'work/outputs/capstone_ranked_actions.json').read_text(encoding='utf-8'))\ndisplay(pd.DataFrame(queue['recommendations'])[['rank','case','review_score','action','reason_codes']])\ndisplay(Image(filename=str(ROOT/'work/figures/capstone_actions.png')))"),
        M("## 7. Limitations and honest framing\n\nThe feature totals and rates overlap the same window as the proxy label. Excluding direct trend fields prevents direct reconstruction, but does not create a future prediction task. The label is a thresholded observed measurement, not editorial utility. The sample contains older pages with impressions and only 32 clients; it may underrepresent new/invisible content and the larger warehouse. Missingness follows content type. Eight held-out clients make subgroup conclusions and bootstrap intervals tentative. Instrumentation differences and seasonality can explain apparent decline. No content text, query intent, intervention records or editorial review outcomes are available. Model scores are not calibrated causal impact probabilities.\n\n**Pending to satisfy the strict full-release brief:** approve Hugging Face access, supply a read token locally, inspect the release manifest and grains, build nonoverlapping historical features and a later observed outcome, and rerun client/time-aware validation. Develop query logic in March 2026 rather than the final-month sample, respect three-valued availability flags, and scan the full release once after query validation. The warehouse plan in the capstone task folder specifies this extension; no future metrics are fabricated."),
        C("print('Pending requirements:')\nfor requirement in study['pending_requirements']:\n    print('-', requirement)"),
        M("## 8. Reproducibility and artifact links\n\nFrom a fresh clone, install repository requirements plus `nbformat`, `nbclient`, and `ipykernel`; run `python work/scripts/capstone_analysis.py`, then execute this notebook top to bottom. The notebook calls the same script and saves deterministic aggregate JSON and four chart PNGs. Seed 2026 and the source SHA-256 are in the metrics file; seed 2027 makes the validation partition. Exact package versions are recorded below. Reference `scripts/` and data remain unchanged.\n\nArtifacts: [metrics](../outputs/capstone_metrics.json), [feature audit](../outputs/capstone_feature_audit.json), [ranked actions](../outputs/capstone_ranked_actions.json), [reproducible analysis](../scripts/capstone_analysis.py), [report](../capstone_report.md). The public repository link and `submission/paper_url.txt` must be finalized only after deployment. The completed local paper must retain all nine required sections and data credit."),
        C("print(json.dumps(study['environment'], indent=2))\nprint('Source SHA-256:', study['data']['source_sha256'])\nassert all(count['clients'] > 0 for count in study['split'].values())\nassert study['leakage_audit']['client_overlap_between_partitions'] == 0\nassert all((ROOT/'work/figures'/name).exists() for name in [\n    'capstone_precision_recall.png','capstone_review_budget.png',\n    'capstone_feature_audit.png','capstone_actions.png'])\nprint('Aggregate outputs and four research figures verified.')"),
        M("## 9. Acknowledgments and data credit\n\n[Built on the FlyRank ML Internship dataset](https://flyrank.ai). Dataset semantics and starter workflow are documented in the supplied FlyRank repository. The baseline adapts the reference weights while fitting transformations within development groups. AI assistance supported code and writing; Hamza Afzal must validate the outputs, decisions and explanations before submission."),
        M("## Demo outline, social draft and employer summary\n\n**Five-minute demo:** 0:00–0:45 name the editor decision and current-proxy limitation; 0:45–1:30 show the 30,000-row safety/grain checks; 1:30–2:30 show grouped validation and the fair baseline/model table; 2:30–3:30 interpret the validation feature audit and metadata ablation; 3:30–4:30 inspect the reason-coded review queue; 4:30–5:00 state what the study cannot prove and the warehouse/deployment requirements.\n\n**Social-post draft (publish only after validation/deployment):** I built a reproducible Ranking Signal Analysis study on the FlyRank starter dataset, with client-held-out evaluation, a transparent rule, model comparisons and explainable content-review suggestions. The measured result describes current-window associations; it does not claim future decline prediction or causal refresh impact. Notebook, paper and source links will be added after publication.\n\n**Employer-facing summary:** This project demonstrates a repeatable Python analysis pipeline with explicit data contracts, group validation and inspectable JSON outputs. It compares learned signals with a transparent rule and turns them into bounded recommendations for human review. The documented limits distinguish reproducible starter findings from an unexecuted warehouse extension."),
        M("## Final self-check\n\n- [x] All paper sections, figures, evidence and data credit authored.\n- [x] Notebook executes top to bottom and regenerates results.\n- [x] No private row export, client identifiers, credentials or causal claims.\n- [x] Model and baseline evaluated on the same group partitions.\n- [ ] Intern validates the scientific framing and first 20 editorial cases.\n- [ ] Full-warehouse extension completes the strict brief's data requirement.\n- [ ] Owned public repo and deployed paper URL verified and submitted.\n\nThese pending items are not marked complete by local execution."),
    ]
    write_notebook(notebooks / "capstone.ipynb", capstone_cells)
    (assignment / "README.md").write_text("# ML-02 — Research Question and Provisional Lane\n\nAuthor: Hamza Afzal.\n\nThe full deliverable is the executed [canonical notebook](../../notebooks/w01_research_question.ipynb). It selects Ranking Signal Analysis, names a page-level editorial decision, actor/action/error cost, fixes evaluation metrics and computes real supporting numbers from the starter CSV. [Measured evidence](../../outputs/research_question_numbers.json) is reproducible using [analysis source](../../scripts/capstone_analysis.py).\n\nLocal preparation and execution are complete. Hamza must validate the framing, commit to his owned public repository and submit its URL; those external requirements are pending.\n", encoding="utf-8")
    (capstone / "README.md").write_text("# Google Search Ranking & Discoverability Capstone\n\nAuthor: Hamza Afzal · Lane: Ranking Signal Analysis.\n\n- [Executed capstone notebook](../../notebooks/capstone.ipynb)\n- [Research paper source](../../capstone_report.md)\n- [Reproducible analysis](../../scripts/capstone_analysis.py)\n- [Aggregate comparison and audit](../../outputs/capstone_metrics.json)\n- [Ranked review cases](../../outputs/capstone_ranked_actions.json)\n- [Warehouse continuation plan](warehouse_extension_plan.md)\n- [Model card](model_card.md)\n\nCompleted local work is a starter-scoped observational study. The strict attached brief's full-warehouse analysis, first-20 human content review, owned public repository, verified deployed paper and submission remain pending. None is represented as already done. No raw datasets belong in this folder.\n", encoding="utf-8")


if __name__ == "__main__":
    build()
    print("Authored ML-02 and capstone canonical notebooks and separate folder indexes.")
